### ISSUE TITLE
Bug: Latest update breaks tag-notes

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#239]
since the latest update (v.2.20), tag-notes have stopped working completely. Link-Notes, Folder-notes and everything else still shows up, but tag-notes do not show up anymore.

**Comment by SkepticMystic** [comment]
@chrisgrieser can you share the configuration of your tag note.
Something like

```yaml
---
BC-tag-note: ' #tag'
BC-tag-note-field: down
---
```
