### ISSUE TITLE
Option to hide "Shortest" button

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#252]
Could you add an option to hide the Shortest button in the Trail view?
I don't see the point of knowing which path is the shortest one. Besides, it's pretty self-evident from the lengths of the paths.
Thank you!

**Comment by SkepticMystic** [comment]
You can achieve this with a CSS snippet :)
```css
.BC-trail button.button-div {
    display: none;
}
```
