### ISSUE TITLE
FR: List/Matrix View: Option/Toggle: Show items as 'unordered list' (bullets instead of numbers)

### ISSUE THREAD

**Issue by avirosso** [SkepticMystic/breadcrumbs#270]
In the 'List/Matrix View', all items are numbered ('ordered list'). IMO it's not necessary, it distracts me. It would be great, to have the option/toggle to change this in 'unordered list', marked with bullets. Thanks in advance!

**Comment by scriptor-dga** [comment]
...or no bullets at all!

**Comment by avirosso** [comment]
If there where "no bullets at all", it would be necessary to indent the second (and third ...) line of long file names (otherwise you couldn't distinguish between a wrapped line and a new item/note) ....

**Comment by SkepticMystic** [comment]
Can I suggest a CSS option?
Using this snippet will make the markers bullets:
```css
.BC-Matrix ol > li::marker {
    content: "-"
}
```
And this one will remove them entirely:
```css
.BC-Matrix ol > li::marker {
    content: ""
}
```
