### ISSUE TITLE
[FR] Floating Breadcrumbs trail view

### ISSUE THREAD

**Issue by dummifiedme** [SkepticMystic/breadcrumbs#304]
Floating breadcrumbs such that the page flows under it. 

OR

If it is floating like the TOC here, it would be really cool.
https://discord.com/channels/686053708261228577/840286264964022302/930827955775631451
https://github.com/curtgrimes/obsidian-floating-toc-plugin

**Comment by SkepticMystic** [comment]
Got quite far with the following CSS:

```css
.BC-page-views {
    position: sticky;
    top: 0px;
    z-index: 99;
}
```
The limitation with this is that the background is transparent, so the content of the note passes thru. I think this can be solved by setting the background-color of the Page Views to the appropriate CSS var
