### ISSUE TITLE
[Feature Request] Toggle to set Matrix links to wrap or trail off with ellipses

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#305]
For those that have notes with long titles, an option to just have the file name trail off might be a good option to avoid having the Matrix View grow incredibly large. 

With css like this you could achieve that:
```css
.BC-Matrix .BC-Link {
    width: 100%;
    padding-right: 10px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

![Obsidian_KkzqCOQFMh](https://user-images.githubusercontent.com/54087190/152188066-61b1354d-8f79-4f40-a8f6-c7ae9d07179c.png)

---
I also recommend a tooltip hover to display the whole title when hovering over the link. 

Like obsidian's tooltip for aliased links, which I think should also be the default behavior for links where breadcrumb shows the aliased title instead of the file title for that link.

![Obsidian_nfRdaTtY9X](https://user-images.githubusercontent.com/54087190/152188886-c5f7af8c-3c54-4067-9781-090fd3c62449.png)
